/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        philosopher: ["Philosopher", "sans-serif"],
        rubik: ["Rubik", "sans-serif"],
        roboto: ["Roboto", "sans-serif"],
        marcellus: ["Marcellus", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        titleType: ["Cairo", "sans-serif"],
        textType: ["Barlow Semi Condensed", " sans-serif"],
        poppins: ["Poppins", "sans-serif"],
      },

      fontSize: {
        header: "45px",
        headerTitle: "50px",
        headerDescription: "18px",
        navBarTitle: "18px",
        navBarTitleWeight: "700",
        footerDescriptionBottomPart: "15px",
        footerDescriptionBottomPartWeight: "400",
        footerCopyRightText: "13px",
        footerCopyRightTextWeight: "500",
        cardHeader: "20px",
        formText: " 14px",
        cardTitle: "24px",
        cardTitleV2: "25px",
        cardBtnText: "16px",
        pHeader: "30px",
      },
      colors: {
        primary: "#1E94E9",
        "primary-dark": "#0678AD",
        "primary-light": "#44CFEE",
        secondary: "#272264",
        "secondary-dark": "#17143C",
        "secondary-light": "#67629A",
        font:"#848484",
        disabled: "#BBC5D3",
        hover: "#ECF3FE",
        "hover-secondary": "#DFECFF",
        "button-yellow": "#F6A60E",
        input: "#D9D9D9",
        background: "#EFF0F6",
        //  'background': '#FFF9F9',
        "login-button": "#0D2446",
        divider: "#848484",
        "bottom-border": "#DEDEDE",
        "label-shadow": "#929292",
        "input-bg": "#F6FAFF",
      },
    },
  },
  plugins: [],
};
